"""Add vil_id column to all tables

Revision ID: 6c66f78feb4b
Revises: ed5f5a51bb29
Create Date: 2025-10-27 06:29:14.891210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c66f78feb4b'
down_revision: Union[str, Sequence[str], None] = 'ed5f5a51bb29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('vil_id', sa.BigInteger(), nullable=True))
    op.add_column('budgets_union', sa.Column('vil_id', sa.BigInteger(), nullable=True))
    op.add_column('ce', sa.Column('vil_id', sa.BigInteger(), nullable=True))
    op.add_column('cgst', sa.Column('vil_id', sa.BigInteger(), nullable=True))
    op.add_column('cu', sa.Column('vil_id', sa.BigInteger(), nullable=True))
    op.add_column('dgft', sa.Column('vil_id', sa.BigInteger(), nullable=True))
    op.add_column('features', sa.Column('vil_id', sa.BigInteger(), nullable=True))
    op.add_column('sgst', sa.Column('vil_id', sa.BigInteger(), nullable=True))
    op.add_column('st', sa.Column('vil_id', sa.BigInteger(), nullable=True))
    op.add_column('vat', sa.Column('vil_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vat', 'vil_id')
    op.drop_column('st', 'vil_id')
    op.drop_column('sgst', 'vil_id')
    op.drop_column('features', 'vil_id')
    op.drop_column('dgft', 'vil_id')
    op.drop_column('cu', 'vil_id')
    op.drop_column('cgst', 'vil_id')
    op.drop_column('ce', 'vil_id')
    op.drop_column('budgets_union', 'vil_id')
    op.drop_column('articles', 'vil_id')
    # ### end Alembic commands ###
