"""Add unique index to vil_id

Revision ID: c0d22a049581
Revises: 6c66f78feb4b
Create Date: 2025-11-12 09:49:33.773144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0d22a049581'
down_revision: Union[str, Sequence[str], None] = '6c66f78feb4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'vil_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_unique_constraint(None, 'articles', ['vil_id'])
    op.alter_column('budgets_union', 'vil_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_unique_constraint(None, 'budgets_union', ['vil_id'])
    op.alter_column('ce', 'vil_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_unique_constraint(None, 'ce', ['vil_id'])
    op.alter_column('cgst', 'vil_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_unique_constraint(None, 'cgst', ['vil_id'])
    op.alter_column('cu', 'vil_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_unique_constraint(None, 'cu', ['vil_id'])
    op.alter_column('dgft', 'vil_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_unique_constraint(None, 'dgft', ['vil_id'])
    op.alter_column('features', 'vil_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_unique_constraint(None, 'features', ['vil_id'])
    op.alter_column('sgst', 'vil_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_unique_constraint(None, 'sgst', ['vil_id'])
    op.alter_column('st', 'vil_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_unique_constraint(None, 'st', ['vil_id'])
    op.alter_column('vat', 'vil_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_unique_constraint(None, 'vat', ['vil_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vat', type_='unique')
    op.alter_column('vat', 'vil_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(None, 'st', type_='unique')
    op.alter_column('st', 'vil_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(None, 'sgst', type_='unique')
    op.alter_column('sgst', 'vil_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(None, 'features', type_='unique')
    op.alter_column('features', 'vil_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(None, 'dgft', type_='unique')
    op.alter_column('dgft', 'vil_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(None, 'cu', type_='unique')
    op.alter_column('cu', 'vil_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(None, 'cgst', type_='unique')
    op.alter_column('cgst', 'vil_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(None, 'ce', type_='unique')
    op.alter_column('ce', 'vil_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(None, 'budgets_union', type_='unique')
    op.alter_column('budgets_union', 'vil_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(None, 'articles', type_='unique')
    op.alter_column('articles', 'vil_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
