"""Create initial tables for all models

Revision ID: ed5f5a51bb29
Revises: 
Create Date: 2025-10-15 14:35:46.280797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed5f5a51bb29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('article_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('article_date', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('file_storage_path', sa.Text(), nullable=False),
    sa.Column('html_file_path', sa.Text(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('updated_dt', sa.DateTime(), nullable=True),
    sa.Column('ingestion_dt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('article_id'),
    sa.UniqueConstraint('html_file_path')
    )
    op.create_index(op.f('ix_articles_article_date'), 'articles', ['article_date'], unique=False)
    op.create_table('budgets_union',
    sa.Column('circular_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('circular_date', sa.DateTime(), nullable=True),
    sa.Column('circular_no', sa.Text(), nullable=True),
    sa.Column('cir_subject', sa.Text(), nullable=True),
    sa.Column('file_storage_path', sa.Text(), nullable=False),
    sa.Column('html_file_path', sa.Text(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('updated_dt', sa.DateTime(), nullable=True),
    sa.Column('ingestion_dt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('circular_id'),
    sa.UniqueConstraint('html_file_path')
    )
    op.create_index(op.f('ix_budgets_union_circular_date'), 'budgets_union', ['circular_date'], unique=False)
    op.create_table('ce',
    sa.Column('case_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prod_id', sa.Text(), nullable=True),
    sa.Column('prod_name', sa.Text(), nullable=True),
    sa.Column('sub_prod_id', sa.Text(), nullable=True),
    sa.Column('sub_prod_name', sa.Text(), nullable=True),
    sa.Column('sub_subprod_id', sa.Text(), nullable=True),
    sa.Column('circular_date', sa.DateTime(), nullable=True),
    sa.Column('eq_citation', sa.Text(), nullable=True),
    sa.Column('circular_no', sa.Text(), nullable=False),
    sa.Column('case_no', sa.Text(), nullable=True),
    sa.Column('order_no', sa.Text(), nullable=True),
    sa.Column('judge_name', sa.Text(), nullable=True),
    sa.Column('cir_subject', sa.Text(), nullable=True),
    sa.Column('party_name', sa.Text(), nullable=True),
    sa.Column('html_file_path', sa.Text(), nullable=False),
    sa.Column('file_storage_path', sa.Text(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('updated_dt', sa.DateTime(), nullable=True),
    sa.Column('ingestion_dt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('case_id'),
    sa.UniqueConstraint('html_file_path')
    )
    op.create_index(op.f('ix_ce_circular_date'), 'ce', ['circular_date'], unique=False)
    op.create_index(op.f('ix_ce_circular_no'), 'ce', ['circular_no'], unique=True)
    op.create_table('cgst',
    sa.Column('case_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prod_id', sa.Text(), nullable=True),
    sa.Column('prod_name', sa.Text(), nullable=True),
    sa.Column('sub_prod_id', sa.Text(), nullable=True),
    sa.Column('sub_prod_name', sa.Text(), nullable=True),
    sa.Column('sub_subprod_id', sa.Text(), nullable=True),
    sa.Column('circular_date', sa.DateTime(), nullable=True),
    sa.Column('circular_no', sa.Text(), nullable=False),
    sa.Column('cir_subject', sa.Text(), nullable=True),
    sa.Column('html_file_path', sa.Text(), nullable=False),
    sa.Column('file_storage_path', sa.Text(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('updated_dt', sa.DateTime(), nullable=True),
    sa.Column('ingestion_dt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('case_id'),
    sa.UniqueConstraint('html_file_path')
    )
    op.create_index(op.f('ix_cgst_circular_date'), 'cgst', ['circular_date'], unique=False)
    op.create_index(op.f('ix_cgst_circular_no'), 'cgst', ['circular_no'], unique=True)
    op.create_table('cu',
    sa.Column('case_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prod_id', sa.Text(), nullable=True),
    sa.Column('prod_name', sa.Text(), nullable=True),
    sa.Column('sub_prod_id', sa.Text(), nullable=True),
    sa.Column('sub_prod_name', sa.Text(), nullable=True),
    sa.Column('sub_subprod_id', sa.Text(), nullable=True),
    sa.Column('circular_date', sa.DateTime(), nullable=True),
    sa.Column('eq_citation', sa.Text(), nullable=True),
    sa.Column('circular_no', sa.Text(), nullable=False),
    sa.Column('case_no', sa.Text(), nullable=True),
    sa.Column('order_no', sa.Text(), nullable=True),
    sa.Column('judge_name', sa.Text(), nullable=True),
    sa.Column('cir_subject', sa.Text(), nullable=True),
    sa.Column('party_name', sa.Text(), nullable=True),
    sa.Column('html_file_path', sa.Text(), nullable=False),
    sa.Column('file_storage_path', sa.Text(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('updated_dt', sa.DateTime(), nullable=True),
    sa.Column('ingestion_dt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('case_id'),
    sa.UniqueConstraint('html_file_path')
    )
    op.create_index(op.f('ix_cu_circular_date'), 'cu', ['circular_date'], unique=False)
    op.create_index(op.f('ix_cu_circular_no'), 'cu', ['circular_no'], unique=True)
    op.create_table('dgft',
    sa.Column('case_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prod_id', sa.Text(), nullable=True),
    sa.Column('prod_name', sa.Text(), nullable=True),
    sa.Column('sub_prod_id', sa.Text(), nullable=True),
    sa.Column('sub_prod_name', sa.Text(), nullable=True),
    sa.Column('sub_subprod_id', sa.Text(), nullable=True),
    sa.Column('state_id', sa.Text(), nullable=True),
    sa.Column('circular_date', sa.DateTime(), nullable=True),
    sa.Column('circular_no', sa.Text(), nullable=False),
    sa.Column('cir_subject', sa.Text(), nullable=True),
    sa.Column('html_file_path', sa.Text(), nullable=False),
    sa.Column('file_storage_path', sa.Text(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('updated_dt', sa.DateTime(), nullable=True),
    sa.Column('ingestion_dt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('case_id'),
    sa.UniqueConstraint('html_file_path')
    )
    op.create_index(op.f('ix_dgft_circular_date'), 'dgft', ['circular_date'], unique=False)
    op.create_index(op.f('ix_dgft_circular_no'), 'dgft', ['circular_no'], unique=True)
    op.create_table('features',
    sa.Column('feature_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('feature_date', sa.DateTime(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('file_storage_path', sa.Text(), nullable=False),
    sa.Column('html_file_path', sa.Text(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('updated_dt', sa.DateTime(), nullable=True),
    sa.Column('ingestion_dt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('feature_id'),
    sa.UniqueConstraint('html_file_path')
    )
    op.create_index(op.f('ix_features_feature_date'), 'features', ['feature_date'], unique=False)
    op.create_table('sgst',
    sa.Column('case_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prod_id', sa.Text(), nullable=True),
    sa.Column('prod_name', sa.Text(), nullable=True),
    sa.Column('sub_prod_id', sa.Text(), nullable=True),
    sa.Column('sub_prod_name', sa.Text(), nullable=True),
    sa.Column('sub_subprod_id', sa.Text(), nullable=True),
    sa.Column('state_id', sa.Text(), nullable=True),
    sa.Column('circular_date', sa.DateTime(), nullable=True),
    sa.Column('eq_citation', sa.Text(), nullable=True),
    sa.Column('section_no', sa.Text(), nullable=True),
    sa.Column('rule_no', sa.Text(), nullable=True),
    sa.Column('igst_section_no', sa.Text(), nullable=True),
    sa.Column('igst_rule_no', sa.Text(), nullable=True),
    sa.Column('circular_no', sa.Text(), nullable=False),
    sa.Column('case_no', sa.Text(), nullable=True),
    sa.Column('order_no', sa.Text(), nullable=True),
    sa.Column('judge_name', sa.Text(), nullable=True),
    sa.Column('cir_subject', sa.Text(), nullable=True),
    sa.Column('party_name', sa.Text(), nullable=True),
    sa.Column('html_file_path', sa.Text(), nullable=False),
    sa.Column('file_storage_path', sa.Text(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('updated_dt', sa.DateTime(), nullable=True),
    sa.Column('ingestion_dt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('case_id'),
    sa.UniqueConstraint('html_file_path')
    )
    op.create_index(op.f('ix_sgst_circular_date'), 'sgst', ['circular_date'], unique=False)
    op.create_index(op.f('ix_sgst_circular_no'), 'sgst', ['circular_no'], unique=True)
    op.create_table('st',
    sa.Column('case_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prod_id', sa.Text(), nullable=True),
    sa.Column('prod_name', sa.Text(), nullable=True),
    sa.Column('sub_prod_id', sa.Text(), nullable=True),
    sa.Column('sub_prod_name', sa.Text(), nullable=True),
    sa.Column('sub_subprod_id', sa.Text(), nullable=True),
    sa.Column('circular_date', sa.DateTime(), nullable=True),
    sa.Column('eq_citation', sa.Text(), nullable=True),
    sa.Column('circular_no', sa.Text(), nullable=False),
    sa.Column('case_no', sa.Text(), nullable=True),
    sa.Column('order_no', sa.Text(), nullable=True),
    sa.Column('judge_name', sa.Text(), nullable=True),
    sa.Column('cir_subject', sa.Text(), nullable=True),
    sa.Column('party_name', sa.Text(), nullable=True),
    sa.Column('html_file_path', sa.Text(), nullable=False),
    sa.Column('file_storage_path', sa.Text(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('updated_dt', sa.DateTime(), nullable=True),
    sa.Column('ingestion_dt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('case_id'),
    sa.UniqueConstraint('html_file_path')
    )
    op.create_index(op.f('ix_st_circular_date'), 'st', ['circular_date'], unique=False)
    op.create_index(op.f('ix_st_circular_no'), 'st', ['circular_no'], unique=True)
    op.create_table('vat',
    sa.Column('case_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prod_id', sa.Text(), nullable=True),
    sa.Column('prod_name', sa.Text(), nullable=True),
    sa.Column('sub_prod_id', sa.Text(), nullable=True),
    sa.Column('sub_prod_name', sa.Text(), nullable=True),
    sa.Column('sub_subprod_id', sa.Text(), nullable=True),
    sa.Column('state_id', sa.Text(), nullable=True),
    sa.Column('circular_date', sa.DateTime(), nullable=True),
    sa.Column('eq_citation', sa.Text(), nullable=True),
    sa.Column('circular_no', sa.Text(), nullable=False),
    sa.Column('case_no', sa.Text(), nullable=True),
    sa.Column('order_no', sa.Text(), nullable=True),
    sa.Column('judge_name', sa.Text(), nullable=True),
    sa.Column('cir_subject', sa.Text(), nullable=True),
    sa.Column('party_name', sa.Text(), nullable=True),
    sa.Column('html_file_path', sa.Text(), nullable=False),
    sa.Column('file_storage_path', sa.Text(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('updated_dt', sa.DateTime(), nullable=True),
    sa.Column('ingestion_dt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('case_id'),
    sa.UniqueConstraint('html_file_path')
    )
    op.create_index(op.f('ix_vat_circular_date'), 'vat', ['circular_date'], unique=False)
    op.create_index(op.f('ix_vat_circular_no'), 'vat', ['circular_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vat_circular_no'), table_name='vat')
    op.drop_index(op.f('ix_vat_circular_date'), table_name='vat')
    op.drop_table('vat')
    op.drop_index(op.f('ix_st_circular_no'), table_name='st')
    op.drop_index(op.f('ix_st_circular_date'), table_name='st')
    op.drop_table('st')
    op.drop_index(op.f('ix_sgst_circular_no'), table_name='sgst')
    op.drop_index(op.f('ix_sgst_circular_date'), table_name='sgst')
    op.drop_table('sgst')
    op.drop_index(op.f('ix_features_feature_date'), table_name='features')
    op.drop_table('features')
    op.drop_index(op.f('ix_dgft_circular_no'), table_name='dgft')
    op.drop_index(op.f('ix_dgft_circular_date'), table_name='dgft')
    op.drop_table('dgft')
    op.drop_index(op.f('ix_cu_circular_no'), table_name='cu')
    op.drop_index(op.f('ix_cu_circular_date'), table_name='cu')
    op.drop_table('cu')
    op.drop_index(op.f('ix_cgst_circular_no'), table_name='cgst')
    op.drop_index(op.f('ix_cgst_circular_date'), table_name='cgst')
    op.drop_table('cgst')
    op.drop_index(op.f('ix_ce_circular_no'), table_name='ce')
    op.drop_index(op.f('ix_ce_circular_date'), table_name='ce')
    op.drop_table('ce')
    op.drop_index(op.f('ix_budgets_union_circular_date'), table_name='budgets_union')
    op.drop_table('budgets_union')
    op.drop_index(op.f('ix_articles_article_date'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
